version: "3"

services:
  mongodb:
    container_name: app-mongodb
    image: mongo:6.0.5
    restart: always
    env_file:
      - .docker.env
    volumes:
      - ./data/db:/data/db
    ports:
      - 27077:27017
